// Writes Supabase configuration into src/environments/*.ts from environment variables
// (loaded from a local .env file in dev, or from real env vars provided by Vercel in production).
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { config } from 'dotenv';

const __dirname = dirname(fileURLToPath(import.meta.url));
const envPath = resolve(__dirname, '../.env');

if (existsSync(envPath)) {
  config({ path: envPath });
}

const supabaseUrl = process.env['SUPABASE_URL'] ?? '';
const supabaseAnonKey = process.env['SUPABASE_ANON_KEY'] ?? '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn(
    '[set-env] SUPABASE_URL and/or SUPABASE_ANON_KEY are not set. Copy .env.example to .env and fill in your Supabase project values.'
  );
}

const targets = [
  { path: resolve(__dirname, '../src/environments/environment.ts'), production: true },
  { path: resolve(__dirname, '../src/environments/environment.development.ts'), production: false },
];

// The environments directory itself is gitignored (only the .env-derived content is generated),
// so a fresh clone (e.g. Vercel) won't have it yet — create it before writing.
mkdirSync(dirname(targets[0].path), { recursive: true });

for (const { path, production } of targets) {
  const content = `// This file is generated by scripts/set-env.mjs from environment variables. Do not edit by hand.
export const environment = {
  production: ${production},
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
};
`;
  writeFileSync(path, content);
}
